steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast2-docker.pkg.dev/$PROJECT_ID/maizeai-repo/frontend",
        "--build-arg",
        "NEXT_PUBLIC_API_BASE_URL=$_NEXT_PUBLIC_API_BASE_URL",
        "./frontend",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast2-docker.pkg.dev/$PROJECT_ID/maizeai-repo/frontend",
      ]

images:
  - "asia-southeast2-docker.pkg.dev/$PROJECT_ID/maizeai-repo/frontend"

options:
  logging: CLOUD_LOGGING_ONLY
