# Konfigurasi Cloud Build untuk build dan deploy aplikasi ke Cloud Run
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast2-docker.pkg.dev/$PROJECT_ID/maizeai-repo/maizeai-app",
        "./backend",
      ]
  # Push image ke Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast2-docker.pkg.dev/$PROJECT_ID/maizeai-repo/maizeai-app",
      ]
  # Deploy ke Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "maizeai-app",
        "--image",
        "asia-southeast2-docker.pkg.dev/$PROJECT_ID/maizeai-repo/maizeai-app",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--set-env-vars",
        "GCS_BUCKET_NAME=cornmodel,GCS_MODEL_BLOB=efficientnetb0_cornmodel.onnx",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
